name: Build Adguard

on:
  # schedule:
  # - cron: "0 2 * * *"
  # # For manual run builds
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Build Adguard Filter
        run: TLS=insecure node src/cli.js -c examples/adguard/configuration.json -o ./optimized/adguard.txt

      - name: Push to repository
        run: |
          git config --global user.name "pkrayzy"
          git config --global user.email "pkrayzy@users.noreply.github.com"
          now=$(date)
          git add -A
          git commit -m "Update Filters on $now"
          git push
